const message = {
  GOOGLE_EARTH_JA : 'Google Earthを開いて',
  HELLO : 'Hello',
  HELLO_JA : 'こんにちは',
  INITIAL_MESSAGE_TITLE : 'こんにちは！',
  INITIAL_MESSAGE_TEXT : 'どのようなご用件でしょうか？ お役に立てたら嬉しいです。',
  BUTTONS_YES : 'Yes',
  BUTTONS_YES_JA : 'はい',
  BUTTONS_NO : 'No',
  BUTTONS_NO_JA : 'いいえ',
  NO_THANKS_JA : '特にありません',
  OK_TELL_ME_AGAIN_JA : 'わかりました。もう一度お願いします。',
  OK_TELL_ME_IF_NEEDED_JA : 'そうですか。。。また何かありましたら教えてください。',
  SEARCH_LOCATION_JA : 'この場所ってどう？',
  SEND_ME_IMAGE : 'その場所の写真を送っていただけますか？',
  SORRY_TELL_ME_AGAIN_JA : 'ごめんなさい！最初からお願いできますか？',
  POSITIVE_PACKAGE_ID : '2',
  POSITIVE_STICKER_ID : '144',
  NEGATIVE_PACKAGE_ID : '2',
  NEGATIVE_STICKER_ID : '38',
  NEUTRAL_PACKAGE_ID : '2',
  NEUTRAL_STICKER_ID : '179',
  UNKNOWN_PACKAGE_ID : '2',
  UNKNOWN_STICKER_ID : '149',
};

export { message }
